name: GCS Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/529515626945/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'github-service-account@plexiform-being-408109.iam.gserviceaccount.com'

    - name: Deploy via GCS
      run: |
        gsutil -m rm -rf gs://git1_bucket/* || echo "$?"
        gsutil -m cp -r * gs://git1_bucket/
